---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles

  tasks:
    - include_tasks: tasks/ansible-setup.yml
    - include_tasks: tasks/pacman.yml

