---
- name: Ensure blacklisted packages are not installed.
  become: true
  pacman:
    name: "{{ item }}"
    state: absent
  with_items: "{{ pacman_uninstalled_packages }}"

- name: Install configured pacman packages.
  become: true
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ pacman_installed_packages }}"
